pub struct Command {
    pub cmd: &'static str,
    pub desc: &'static str,
    pub example: &'static str,
    pub danger: bool,
    pub note: &'static str,
}

pub struct Category {
    pub name: &'static str,
    pub commands: &'static [Command],
}

pub static CATEGORIES: &[Category] = &[
    Category {
        name: "Setup & Config",
        commands: &[
            Command {
                cmd: "git config --global user.name \"<name>\"",
                desc: "Set global username for all commits",
                example: "git config --global user.name \"John Doe\"",
                danger: false,
                note: "Stored in ~/.gitconfig",
            },
            Command {
                cmd: "git config --global user.email \"<email>\"",
                desc: "Set global email for all commits",
                example: "git config --global user.email \"john@example.com\"",
                danger: false,
                note: "Required for every commit",
            },
            Command {
                cmd: "git config --global core.editor <editor>",
                desc: "Set default editor (vim, nano, code)",
                example: "git config --global core.editor vim",
                danger: false,
                note: "Used for commit messages",
            },
            Command {
                cmd: "git config --global color.ui auto",
                desc: "Enable helpful colorization in output",
                example: "git config --global color.ui auto",
                danger: false,
                note: "Highly recommended for readability",
            },
            Command {
                cmd: "git config --list",
                desc: "Show all current configuration values",
                example: "git config --list\ngit config --list --show-origin",
                danger: false,
                note: "Shows global + local merged",
            },
            Command {
                cmd: "git config --global alias.<alias> <cmd>",
                desc: "Create a command shortcut alias",
                example: "git config --global alias.st status\ngit config --global alias.lg \"log --oneline --graph\"",
                danger: false,
                note: "Access via git <alias>",
            },
            Command {
                cmd: "git config --global init.defaultBranch main",
                desc: "Set default branch name to main",
                example: "git config --global init.defaultBranch main",
                danger: false,
                note: "Avoids 'master' on new repos",
            },
            Command {
                cmd: "git config --global credential.helper store",
                desc: "Save credentials to disk to avoid re-entering",
                example: "git config --global credential.helper store\ngit config --global credential.helper cache",
                danger: false,
                note: "cache stores temporarily, store saves to file",
            },
        ],
    },
    Category {
        name: "Starting a Repo",
        commands: &[
            Command {
                cmd: "git init",
                desc: "Initialize a new local repository",
                example: "git init\ngit init my-project",
                danger: false,
                note: "Creates hidden .git directory",
            },
            Command {
                cmd: "git init <directory>",
                desc: "Create a new repo in a named folder",
                example: "git init my-project",
                danger: false,
                note: "Creates the folder if it doesn't exist",
            },
            Command {
                cmd: "git clone <url>",
                desc: "Clone a remote repository locally",
                example: "git clone https://example.com/user/repo.git\ngit clone git@example.com:user/repo.git",
                danger: false,
                note: "Copies full history and all branches",
            },
            Command {
                cmd: "git clone <url> <directory>",
                desc: "Clone into a specific folder name",
                example: "git clone https://example.com/user/repo.git my-dir",
                danger: false,
                note: "Useful to rename on clone",
            },
            Command {
                cmd: "git clone --depth 1 <url>",
                desc: "Clone only the latest commit (shallow clone)",
                example: "git clone --depth 1 https://example.com/user/repo.git",
                danger: false,
                note: "Much faster for large repos you just need to build",
            },
        ],
    },
    Category {
        name: "Basic Workflow",
        commands: &[
            Command {
                cmd: "git status",
                desc: "Show working tree and staging area status",
                example: "git status\ngit status -s",
                danger: false,
                note: "-s gives compact short format",
            },
            Command {
                cmd: "git add <file>",
                desc: "Stage a specific file for commit",
                example: "git add README.md\ngit add src/main.rs",
                danger: false,
                note: "Use . to stage everything",
            },
            Command {
                cmd: "git add .",
                desc: "Stage all changes in current directory",
                example: "git add .",
                danger: false,
                note: "Includes new, modified, deleted",
            },
            Command {
                cmd: "git add -p",
                desc: "Interactively stage chunks of changes",
                example: "git add -p\ngit add --patch src/main.rs",
                danger: false,
                note: "Lets you choose which changes to stage, hunk by hunk",
            },
            Command {
                cmd: "git commit -m \"<message>\"",
                desc: "Commit staged changes with a message",
                example: "git commit -m \"feat: add login page\"",
                danger: false,
                note: "Use imperative mood in message",
            },
            Command {
                cmd: "git commit -am \"<message>\"",
                desc: "Stage tracked files and commit in one step",
                example: "git commit -am \"fix: correct typo in README\"",
                danger: false,
                note: "Does not include untracked files",
            },
            Command {
                cmd: "git commit --amend",
                desc: "Modify the most recent commit",
                example: "git commit --amend\ngit commit --amend -m \"updated message\"",
                danger: true,
                note: "Never amend pushed commits",
            },
            Command {
                cmd: "git diff",
                desc: "Show unstaged changes in working tree",
                example: "git diff\ngit diff src/main.rs",
                danger: false,
                note: "Compares working tree to index",
            },
            Command {
                cmd: "git diff --staged",
                desc: "Show staged changes vs last commit",
                example: "git diff --staged",
                danger: false,
                note: "Also: --cached (same thing)",
            },
            Command {
                cmd: "git diff <branch1>..<branch2>",
                desc: "Compare two branches",
                example: "git diff main..feature/login",
                danger: false,
                note: "Shows what's in branch2 not branch1",
            },
            Command {
                cmd: "git rm <file>",
                desc: "Remove file from repo and working tree",
                example: "git rm old-file.txt\ngit rm --cached secret.env",
                danger: true,
                note: "--cached removes tracking only, keeps file",
            },
            Command {
                cmd: "git mv <old> <new>",
                desc: "Move or rename a file and stage the change",
                example: "git mv old-name.rs new-name.rs\ngit mv src/file.rs lib/file.rs",
                danger: false,
                note: "Without this, git sees a delete + add",
            },
        ],
    },
    Category {
        name: "Branching",
        commands: &[
            Command {
                cmd: "git branch",
                desc: "List all local branches",
                example: "git branch",
                danger: false,
                note: "Active branch marked with *",
            },
            Command {
                cmd: "git branch -a",
                desc: "List all branches including remote",
                example: "git branch -a",
                danger: false,
                note: "Remote branches shown as remotes/<name>",
            },
            Command {
                cmd: "git branch <name>",
                desc: "Create a new branch at current HEAD",
                example: "git branch feature/dark-mode",
                danger: false,
                note: "Does not switch to the new branch",
            },
            Command {
                cmd: "git branch -d <name>",
                desc: "Delete a merged branch safely",
                example: "git branch -d feature/done",
                danger: false,
                note: "Fails if branch has unmerged commits",
            },
            Command {
                cmd: "git branch -D <name>",
                desc: "Force delete branch regardless of merge status",
                example: "git branch -D feature/abandoned",
                danger: true,
                note: "Commits may be lost permanently",
            },
            Command {
                cmd: "git branch -m <old> <new>",
                desc: "Rename a branch",
                example: "git branch -m old-name new-name",
                danger: false,
                note: "Also updates remote if you push after",
            },
            Command {
                cmd: "git switch <branch>",
                desc: "Switch to an existing branch",
                example: "git switch main",
                danger: false,
                note: "Modern replacement for checkout (git 2.23+)",
            },
            Command {
                cmd: "git switch -c <branch>",
                desc: "Create and switch to a new branch",
                example: "git switch -c feature/user-auth",
                danger: false,
                note: "Modern replacement for checkout -b",
            },
            Command {
                cmd: "git checkout <branch>",
                desc: "Switch to an existing branch (classic)",
                example: "git checkout main",
                danger: false,
                note: "Also used to restore files",
            },
            Command {
                cmd: "git checkout -b <branch>",
                desc: "Create and switch to new branch (classic)",
                example: "git checkout -b feature/api",
                danger: false,
                note: "Equivalent to switch -c",
            },
            Command {
                cmd: "git merge <branch>",
                desc: "Merge a branch into the current branch",
                example: "git merge feature/login\ngit merge --no-ff feature/login",
                danger: false,
                note: "--no-ff preserves branch history",
            },
            Command {
                cmd: "git merge --squash <branch>",
                desc: "Squash all commits from branch into one staged change",
                example: "git merge --squash feature/wip",
                danger: false,
                note: "Then commit manually to finalize",
            },
            Command {
                cmd: "git merge --abort",
                desc: "Abort an in-progress merge",
                example: "git merge --abort",
                danger: false,
                note: "Returns to pre-merge state",
            },
            Command {
                cmd: "git rebase <branch>",
                desc: "Reapply commits on top of another branch",
                example: "git rebase main",
                danger: true,
                note: "Never rebase branches others have pulled",
            },
            Command {
                cmd: "git rebase -i HEAD~<n>",
                desc: "Interactively rebase last N commits",
                example: "git rebase -i HEAD~3",
                danger: true,
                note: "Squash, reorder, edit, drop commits",
            },
            Command {
                cmd: "git rebase --abort",
                desc: "Abort an in-progress rebase",
                example: "git rebase --abort",
                danger: false,
                note: "Returns to pre-rebase state",
            },
            Command {
                cmd: "git rebase --continue",
                desc: "Continue rebase after resolving conflicts",
                example: "git rebase --continue",
                danger: false,
                note: "Stage resolved files first",
            },
        ],
    },
    Category {
        name: "Remote",
        commands: &[
            Command {
                cmd: "git remote -v",
                desc: "List all remote connections with URLs",
                example: "git remote -v",
                danger: false,
                note: "Shows fetch and push URLs",
            },
            Command {
                cmd: "git remote add <name> <url>",
                desc: "Add a new remote connection",
                example: "git remote add origin https://example.com/user/repo.git",
                danger: false,
                note: "origin is the conventional default name",
            },
            Command {
                cmd: "git remote remove <name>",
                desc: "Remove a remote connection",
                example: "git remote remove origin",
                danger: false,
                note: "Does not delete the remote repo",
            },
            Command {
                cmd: "git remote rename <old> <new>",
                desc: "Rename a remote",
                example: "git remote rename origin upstream",
                danger: false,
                note: "Updates local tracking references",
            },
            Command {
                cmd: "git remote set-url <name> <url>",
                desc: "Change URL of an existing remote",
                example: "git remote set-url origin https://example.com/user/repo.git",
                danger: false,
                note: "Useful when switching from HTTPS to SSH or vice versa",
            },
            Command {
                cmd: "git fetch <remote>",
                desc: "Download remote changes without merging",
                example: "git fetch origin\ngit fetch --all",
                danger: false,
                note: "Safe; never modifies working tree",
            },
            Command {
                cmd: "git fetch --prune",
                desc: "Fetch and remove stale remote-tracking branches",
                example: "git fetch --prune",
                danger: false,
                note: "Cleans up deleted remote branches",
            },
            Command {
                cmd: "git pull",
                desc: "Fetch and merge remote branch into current",
                example: "git pull\ngit pull origin main",
                danger: false,
                note: "Equivalent to fetch + merge",
            },
            Command {
                cmd: "git pull --rebase",
                desc: "Fetch and rebase instead of merge",
                example: "git pull --rebase origin main",
                danger: false,
                note: "Keeps history linear, avoids merge commits",
            },
            Command {
                cmd: "git push <remote> <branch>",
                desc: "Push branch to remote repository",
                example: "git push origin main\ngit push origin feature/login",
                danger: false,
                note: "Remote must be configured first",
            },
            Command {
                cmd: "git push -u <remote> <branch>",
                desc: "Push and set upstream tracking",
                example: "git push -u origin feature/new",
                danger: false,
                note: "After this, plain git push works",
            },
            Command {
                cmd: "git push --force-with-lease",
                desc: "Safer force push, fails if remote changed",
                example: "git push --force-with-lease origin feature",
                danger: true,
                note: "Safer than --force; prevents overwriting others",
            },
            Command {
                cmd: "git push --delete <remote> <branch>",
                desc: "Delete a remote branch",
                example: "git push --delete origin old-feature",
                danger: true,
                note: "Also: git push origin :branch-name",
            },
            Command {
                cmd: "git push --tags",
                desc: "Push all local tags to remote",
                example: "git push origin --tags",
                danger: false,
                note: "Tags are not pushed by default",
            },
        ],
    },
    Category {
        name: "Undo & Fix",
        commands: &[
            Command {
                cmd: "git restore <file>",
                desc: "Discard unstaged changes in working tree",
                example: "git restore src/main.rs\ngit restore .",
                danger: true,
                note: "Changes are permanently discarded",
            },
            Command {
                cmd: "git restore --staged <file>",
                desc: "Unstage a file without discarding changes",
                example: "git restore --staged README.md",
                danger: false,
                note: "Equivalent to old: git reset HEAD <file>",
            },
            Command {
                cmd: "git reset --soft HEAD~<n>",
                desc: "Undo last N commits, keep changes staged",
                example: "git reset --soft HEAD~1",
                danger: false,
                note: "Safest reset; no data lost",
            },
            Command {
                cmd: "git reset --mixed HEAD~<n>",
                desc: "Undo last N commits, keep changes unstaged",
                example: "git reset --mixed HEAD~2",
                danger: false,
                note: "Default mode if no flag given",
            },
            Command {
                cmd: "git reset --hard HEAD~<n>",
                desc: "Undo last N commits and discard all changes",
                example: "git reset --hard HEAD~1",
                danger: true,
                note: "Permanently destroys uncommitted work",
            },
            Command {
                cmd: "git reset --hard <commit>",
                desc: "Reset HEAD to a specific commit",
                example: "git reset --hard abc1234",
                danger: true,
                note: "Use git reflog to find lost commits",
            },
            Command {
                cmd: "git revert <commit>",
                desc: "Create a new commit that undoes a commit",
                example: "git revert HEAD\ngit revert abc1234",
                danger: false,
                note: "Safe for shared branches, no history rewrite",
            },
            Command {
                cmd: "git revert --no-commit <commit>",
                desc: "Stage revert changes without committing",
                example: "git revert --no-commit HEAD~3..HEAD",
                danger: false,
                note: "Review before finalizing the revert",
            },
            Command {
                cmd: "git clean -n",
                desc: "Dry run, preview untracked files to delete",
                example: "git clean -n\ngit clean -nd",
                danger: false,
                note: "Always run -n before -f",
            },
            Command {
                cmd: "git clean -fd",
                desc: "Delete untracked files and directories",
                example: "git clean -fd",
                danger: true,
                note: "Permanently removes untracked files",
            },
            Command {
                cmd: "git reflog",
                desc: "Show history of all HEAD movements",
                example: "git reflog\ngit checkout HEAD@{3}",
                danger: false,
                note: "Your safety net. Entries expire after 90 days",
            },
        ],
    },
    Category {
        name: "Stash",
        commands: &[
            Command {
                cmd: "git stash",
                desc: "Save dirty working state to stash stack",
                example: "git stash\ngit stash push -m \"wip: login form\"",
                danger: false,
                note: "Only saves tracked files. Use -u for untracked",
            },
            Command {
                cmd: "git stash push -u",
                desc: "Stash including untracked files",
                example: "git stash push -u -m \"including new files\"",
                danger: false,
                note: "-u includes untracked, -a includes ignored",
            },
            Command {
                cmd: "git stash list",
                desc: "List all stashed entries",
                example: "git stash list",
                danger: false,
                note: "Shows stash@{0}, stash@{1} etc.",
            },
            Command {
                cmd: "git stash show <stash>",
                desc: "Show diff summary of a stash entry",
                example: "git stash show stash@{0}\ngit stash show -p",
                danger: false,
                note: "-p shows full patch diff",
            },
            Command {
                cmd: "git stash pop",
                desc: "Apply latest stash and remove it from stack",
                example: "git stash pop\ngit stash pop stash@{2}",
                danger: false,
                note: "Use apply to keep the stash entry",
            },
            Command {
                cmd: "git stash apply <stash>",
                desc: "Apply a stash without removing it",
                example: "git stash apply stash@{1}",
                danger: false,
                note: "Stash entry remains after apply",
            },
            Command {
                cmd: "git stash drop <stash>",
                desc: "Delete a specific stash entry",
                example: "git stash drop stash@{0}\ngit stash clear",
                danger: true,
                note: "clear removes ALL stash entries",
            },
            Command {
                cmd: "git stash branch <branch> <stash>",
                desc: "Create a branch from a stash entry",
                example: "git stash branch fix/from-stash stash@{0}",
                danger: false,
                note: "Applies stash to new branch and drops it",
            },
        ],
    },
    Category {
        name: "Tags",
        commands: &[
            Command {
                cmd: "git tag",
                desc: "List all tags",
                example: "git tag\ngit tag -l \"v1.*\"",
                danger: false,
                note: "-l with pattern filters by name",
            },
            Command {
                cmd: "git tag <name>",
                desc: "Create a lightweight tag at HEAD",
                example: "git tag v1.0.0",
                danger: false,
                note: "Lightweight tag, just a pointer",
            },
            Command {
                cmd: "git tag -a <name> -m \"<msg>\"",
                desc: "Create an annotated tag with message",
                example: "git tag -a v1.0.0 -m \"First stable release\"",
                danger: false,
                note: "Annotated tags store tagger, date, message",
            },
            Command {
                cmd: "git tag -d <name>",
                desc: "Delete a local tag",
                example: "git tag -d v1.0.0-rc",
                danger: true,
                note: "Doesn't delete from remote",
            },
            Command {
                cmd: "git push origin <tag>",
                desc: "Push a specific tag to remote",
                example: "git push origin v1.0.0\ngit push origin --tags",
                danger: false,
                note: "Tags are not pushed by default",
            },
            Command {
                cmd: "git push origin --delete <tag>",
                desc: "Delete a tag from remote",
                example: "git push origin --delete v0.9-beta",
                danger: true,
                note: "Local tag still exists after this",
            },
        ],
    },
    Category {
        name: "History & Diff",
        commands: &[
            Command {
                cmd: "git log",
                desc: "Show full commit history",
                example: "git log\ngit log -10",
                danger: false,
                note: "-n limits to last n commits",
            },
            Command {
                cmd: "git log --oneline --graph --all",
                desc: "Visual graph of all branches and commits",
                example: "git log --oneline --graph --all --decorate",
                danger: false,
                note: "Best way to visualize branch topology",
            },
            Command {
                cmd: "git log -p",
                desc: "Show commit history with diffs",
                example: "git log -p\ngit log -p -5",
                danger: false,
                note: "-5 limits to 5 most recent",
            },
            Command {
                cmd: "git log --author=\"<name>\"",
                desc: "Filter history by author",
                example: "git log --author=\"Ada\"",
                danger: false,
                note: "Accepts partial name match",
            },
            Command {
                cmd: "git log --since=<date>",
                desc: "Show commits after a date",
                example: "git log --since=\"2 weeks ago\"\ngit log --since=\"2024-01-01\"",
                danger: false,
                note: "Combine with --until for range",
            },
            Command {
                cmd: "git log --grep=\"<pattern>\"",
                desc: "Search commit messages by pattern",
                example: "git log --grep=\"fix:\"",
                danger: false,
                note: "Use -i for case-insensitive",
            },
            Command {
                cmd: "git log -- <file>",
                desc: "Show history for a specific file",
                example: "git log -- src/main.rs\ngit log -p -- README.md",
                danger: false,
                note: "Works even for deleted files",
            },
            Command {
                cmd: "git log --follow <file>",
                desc: "Track file history through renames",
                example: "git log --follow src/app.rs",
                danger: false,
                note: "Without --follow, history stops at the rename",
            },
            Command {
                cmd: "git log <branch1>..<branch2>",
                desc: "Show commits in branch2 not in branch1",
                example: "git log main..feature/login",
                danger: false,
                note: "Useful for PR review",
            },
            Command {
                cmd: "git show <commit>",
                desc: "Show details and diff of a commit",
                example: "git show HEAD\ngit show abc1234",
                danger: false,
                note: "Shows metadata + full diff",
            },
            Command {
                cmd: "git show <commit>:<file>",
                desc: "Show a file's content at a specific commit",
                example: "git show HEAD~2:src/main.rs",
                danger: false,
                note: "Does not affect working tree",
            },
            Command {
                cmd: "git blame <file>",
                desc: "Show who last modified each line of a file",
                example: "git blame src/app.rs\ngit blame -L 10,30 main.rs",
                danger: false,
                note: "-L limits to a line range",
            },
            Command {
                cmd: "git shortlog -sn",
                desc: "Summarize commit count by author",
                example: "git shortlog -sn\ngit shortlog -sn --no-merges",
                danger: false,
                note: "-s count only, -n sort by number",
            },
            Command {
                cmd: "git diff <commit1> <commit2>",
                desc: "Show diff between two commits",
                example: "git diff abc1234 def5678",
                danger: false,
                note: "Order matters; shows what changed",
            },
            Command {
                cmd: "git diff HEAD~1",
                desc: "Show diff from one commit ago",
                example: "git diff HEAD~1\ngit diff HEAD~3 HEAD",
                danger: false,
                note: "Tilde notation works on any ref",
            },
            Command {
                cmd: "git diff --stat",
                desc: "Show diff summary with file stats",
                example: "git diff --stat main\ngit diff --stat HEAD~5",
                danger: false,
                note: "Shows files changed + insertions/deletions",
            },
            Command {
                cmd: "git grep <pattern>",
                desc: "Search working tree for a string",
                example: "git grep \"TODO\"\ngit grep -n \"fn main\"",
                danger: false,
                note: "-n shows line numbers",
            },
            Command {
                cmd: "git bisect start",
                desc: "Start binary search to find a bad commit",
                example: "git bisect start\ngit bisect bad\ngit bisect good v1.0",
                danger: false,
                note: "Mark commits good/bad to narrow down",
            },
            Command {
                cmd: "git bisect reset",
                desc: "End bisect session and return to HEAD",
                example: "git bisect reset",
                danger: false,
                note: "Always run this when done",
            },
        ],
    },
    Category {
        name: "Cleanup & Maintenance",
        commands: &[
            Command {
                cmd: "git gc",
                desc: "Run garbage collection to optimize repo",
                example: "git gc\ngit gc --aggressive",
                danger: false,
                note: "--aggressive is slower but thorough",
            },
            Command {
                cmd: "git prune",
                desc: "Remove unreachable objects from object db",
                example: "git prune\ngit prune --dry-run",
                danger: true,
                note: "Usually handled automatically by gc",
            },
            Command {
                cmd: "git fsck",
                desc: "Verify integrity of the object database",
                example: "git fsck\ngit fsck --unreachable",
                danger: false,
                note: "Useful for diagnosing corruption",
            },
            Command {
                cmd: "git archive <branch>",
                desc: "Create a tar/zip archive of a branch",
                example: "git archive --format=zip HEAD > release.zip\ngit archive main | tar -x -C /tmp/export",
                danger: false,
                note: "Does not include .git directory",
            },
            Command {
                cmd: "git submodule add <url>",
                desc: "Add a repository as a submodule",
                example: "git submodule add https://example.com/user/lib.git libs/lib",
                danger: false,
                note: "Creates .gitmodules entry",
            },
            Command {
                cmd: "git submodule update --init --recursive",
                desc: "Initialize and update all submodules",
                example: "git submodule update --init --recursive",
                danger: false,
                note: "Run this after cloning repos with submodules",
            },
            Command {
                cmd: "git lfs track \"<pattern>\"",
                desc: "Track large files with Git LFS",
                example: "git lfs track \"*.psd\"\ngit lfs track \"*.mp4\"",
                danger: false,
                note: "Requires git-lfs to be installed",
            },
            Command {
                cmd: ".gitignore",
                desc: "File listing patterns git should ignore",
                example: "# in .gitignore:\n*.log\nnode_modules/\n.env\ndist/",
                danger: false,
                note: "Per-repo; ~/.gitignore_global for global",
            },
        ],
    },
    Category {
        name: "Worktrees",
        commands: &[
            Command {
                cmd: "git worktree add <path> <branch>",
                desc: "Check out a branch in a new directory",
                example: "git worktree add ../hotfix hotfix/urgent",
                danger: false,
                note: "Multiple checkouts of same repo",
            },
            Command {
                cmd: "git worktree add -b <branch> <path>",
                desc: "Create new branch and check it out in dir",
                example: "git worktree add -b feature/new ../feature-dir",
                danger: false,
                note: "Convenient for parallel work",
            },
            Command {
                cmd: "git worktree list",
                desc: "List all linked worktrees",
                example: "git worktree list",
                danger: false,
                note: "Shows path, HEAD, and branch",
            },
            Command {
                cmd: "git worktree remove <path>",
                desc: "Remove a linked worktree directory",
                example: "git worktree remove ../hotfix",
                danger: false,
                note: "Directory must be clean first",
            },
            Command {
                cmd: "git worktree prune",
                desc: "Clean up stale worktree references",
                example: "git worktree prune",
                danger: false,
                note: "Run after manually deleting worktree dirs",
            },
            Command {
                cmd: "git worktree lock <path>",
                desc: "Lock a worktree to prevent pruning",
                example: "git worktree lock ../hotfix",
                danger: false,
                note: "Useful for worktrees on removable media",
            },
            Command {
                cmd: "git worktree unlock <path>",
                desc: "Unlock a previously locked worktree",
                example: "git worktree unlock ../hotfix",
                danger: false,
                note: "",
            },
            Command {
                cmd: "git worktree move <src> <dst>",
                desc: "Move a worktree to a new path",
                example: "git worktree move ../old-dir ../new-dir",
                danger: false,
                note: "Updates internal references automatically",
            },
        ],
    },
    Category {
        name: "Advanced Branching",
        commands: &[
            Command {
                cmd: "git cherry-pick <commit>",
                desc: "Apply a specific commit onto current branch",
                example: "git cherry-pick abc1234\ngit cherry-pick abc..def",
                danger: false,
                note: "Useful for porting hotfixes between branches",
            },
            Command {
                cmd: "git cherry-pick --no-commit <commit>",
                desc: "Apply commit changes without committing",
                example: "git cherry-pick --no-commit abc1234",
                danger: false,
                note: "Stage changes for review before committing",
            },
            Command {
                cmd: "git cherry-pick --abort",
                desc: "Abort an in-progress cherry-pick",
                example: "git cherry-pick --abort",
                danger: false,
                note: "Returns to pre-cherry-pick state",
            },
            Command {
                cmd: "git merge-base <branch1> <branch2>",
                desc: "Find the common ancestor of two branches",
                example: "git merge-base main feature/login",
                danger: false,
                note: "Returns commit SHA of the common ancestor",
            },
            Command {
                cmd: "git rerere",
                desc: "Reuse recorded conflict resolutions",
                example: "git config --global rerere.enabled true\ngit rerere",
                danger: false,
                note: "Automates resolving repeated merge conflicts",
            },
        ],
    },
    Category {
        name: "Getting Help",
        commands: &[
            Command {
                cmd: "git help <command>",
                desc: "Open the manual page for a command",
                example: "git help commit\ngit help rebase",
                danger: false,
                note: "Opens full docs in your pager",
            },
            Command {
                cmd: "git <command> -h",
                desc: "Show quick usage summary in terminal",
                example: "git commit -h\ngit stash -h",
                danger: false,
                note: "Shorter than full help, good for quick reference",
            },
        ],
    },
];
